# Generated by Django 4.2.23 on 2025-11-11 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_salesinvoice_options_and_more'),
    ]

    operations = [
        # migrations.RenameIndex(
        #     model_name='salesinvoice',
        #     new_name='sales_sales_status_8766e4_idx',
        #     old_name='idx_salesinvoice_status_date',
        # ),
    ]
