# Generated by Django 4.2 on 2025-12-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salesinvoice_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
