# Generated by Django 4.2 on 2025-12-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_add_doctor_name_to_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesline',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
