# Generated by Django 4.2 on 2025-12-11 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_add_hsn_code_to_salesline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesline',
            name='hsn_code',
        ),
    ]
