# Generated by Django 4.2 on 2025-11-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsx', '0004_payment_masters'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD_CREDIT', 'Card - Credit'), ('CARD_DEBIT', 'Card - Debit'), ('NET_BANKING', 'Net Banking'), ('CREDIT', 'On Credit'), ('OTHER', 'Other')], default='OTHER', max_length=32),
        ),
    ]
