# Generated by Django 4.2.7 on 2025-12-15 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userdevice_ip_address_and_more'),
        ('settingsx', '0008_alter_taxbillingsettings_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedInvoiceNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=64, unique=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
            options={
                'ordering': ['-deleted_at'],
                'indexes': [models.Index(fields=['-deleted_at'], name='settingsx_d_deleted_c6a50f_idx')],
            },
        ),
    ]
