# Generated by Django 4.2.7 on 2025-12-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsx', '0009_deletedinvoicenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedinvoicenumber',
            name='original_invoice_date',
            field=models.DateTimeField(blank=True, help_text='Original invoice date to preserve chronological order', null=True),
        ),
    ]
