# Generated by Django 4.2.7 on 2025-12-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsx', '0010_deletedinvoicenumber_original_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedinvoicenumber',
            name='is_reused',
            field=models.BooleanField(default=False, help_text='Mark as True when this invoice number is reused'),
        ),
    ]
