# Generated by Django 4.2.7 on 2025-12-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsx', '0011_deletedinvoicenumber_is_reused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedinvoicenumber',
            name='invoice_no',
            field=models.CharField(max_length=64),
        ),
    ]
