# Generated by Django 4.2 on 2025-11-25 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_productcategory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='medicine_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.medicineform'),
        ),
    ]
