# Generated by Django 4.2 on 2025-11-25 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_medicine_form'),
        ('procurement', '0002_alter_purchase_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptline',
            name='new_product_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='rack_no',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='medicine_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.medicineform'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='requested_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='goodsreceiptline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.product'),
        ),
    ]
