# Generated by Django 4.2 on 2025-12-05 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_batchlot_initial_quantity_and_more'),
        ('procurement', '0007_remove_purchaseorderline_medicine_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='medicine_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.medicineform'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.product'),
        ),
    ]
