# Generated by Django 4.2.23 on 2025-12-03 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_passwordresetotp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_reset_otps', to=settings.AUTH_USER_MODEL),
        ),
    ]
