# Generated by Django 4.2.23 on 2025-11-07 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_h1registerentry_balance_after_issue_base_and_more'),
        ('compliance', '0002_initial'),
    ]

    operations = [
    ]
