# Generated by Django 4.2.23 on 2025-11-07 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_delete_customerserializer_alter_customer_name_and_more'),
        ('customers', '0003_alter_customer_name_alter_customer_phone'),
    ]

    operations = [
    ]
