# Generated by Django 4.2 on 2025-11-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_batchstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='racklocation',
            name='current_capacity',
            field=models.PositiveIntegerField(default=0, help_text='Current occupied capacity units'),
        ),
        migrations.AddField(
            model_name='racklocation',
            name='max_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Optional maximum capacity for the rack', null=True),
        ),
    ]
